require("dotenv").config();
const pgConfig = {
    user: process.env.DB_USER,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    ssl: {
        rejectUnauthorized: true,
        ca: `-----BEGIN CERTIFICATE-----
MIIEQTCCAqmgAwIBAgIUVBVgyQ2EK+y/T3gKdy5KSY4K6NkwDQYJKoZIhvcNAQEM
BQAwOjE4MDYGA1UEAwwvMmI3ZWFkMDgtYTllNC00NjE3LWI2YWQtYTVmNzViMzZm
NTg4IFByb2plY3QgQ0EwHhcNMjQwMjA4MTMxMzUxWhcNMzQwMjA1MTMxMzUxWjA6
MTgwNgYDVQQDDC8yYjdlYWQwOC1hOWU0LTQ2MTctYjZhZC1hNWY3NWIzNmY1ODgg
UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAKODVpmb
ngiUpUZKqwqEXfQom3MklBbLBOTW81mSjC7hukPtaT3fuxq/rmdUdWApcO9QUA/Z
83Ak7/OOt9Hjp+0stbLWHHlFpEI/Bz6opZTQEUFbOqTx/tVwv9bttbFIqui0OrxA
bgG/f4Gx7CNHu0Powvk9hkNoMUVLFOPgj0CvPoWHG1oR46phnPaBjBCAnZjEOkSI
Z4ZE1ayS2MJmk8xVta25SMDLAWUnqMT7hWK1819YCFT5CyQCqJ6cQG/TdQqpJn5v
BRUuiT2Suskxx6+ZPQn9xf8tP6vMXfFfewcf96BNEycbtXPrBSxsdCoBe6yBAXIX
2IVWYRvr8isFVdKKukb3XiWESZ+KxeLBUE4uqkvLH6hqYnFrnWfZnYVjLLHwO/4B
LlCXpj+fYptf99QBvWB8b15PizmYl+uuoX5xltkuD0QiW5VBhqRvK7cNqFDbXZ6m
d/m+3PcUkZjIpf8qCAlFOzdCPi92GHjn2MwsEe5KGiMYHSP7O3rQWHu5cQIDAQAB
oz8wPTAdBgNVHQ4EFgQUhrAjI4wEstGbVlyBh96shjGdAZ0wDwYDVR0TBAgwBgEB
/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAEvQeckSnKsG43rs
7r6sadNR04OfWvDh2hfXmGMZrQTZWCrV1UcvSuq3VMRM+wDRKstQt/o0tTEUC8/p
WAnXAVm0n7EdcfdGzn3BPg5+Kr4xApp29ZVAuE7vRXRCud2swoNGXSn4DAPSqYlo
UqPJuBn+nSMMapIP0vJx+R/0sHaf1ZMVdSoJLAviri7I0EbsxdhCLwXXcpmt2evx
HRVAMtRyxwd2mHFxI3A0EYVfwwvezBVV8i3sK85yIhu7s68tMIBn1F2TfqAC5sOv
qe63g7nr0C9f7O+t9vbmWrfIHFJ+XZsH9CUSup0xTQJwO6hVl3vRS0m4rM9C1wzS
mXv6WizpAPhtIA3tumUFwdpb+e28vo3GQJ/Wy6A5XJuIPYKwBZrUuPKjGo6+BOtu
GSgGzNUpnbGYNs/HwMBr3kuwLwCoXSrUJkpWZJHXyaiXwBivI9QtgJC0G5eW+P2s
tisqA61bVtYyfN5DV/1ufbtNW0Im2yECEKp+zoUYU0ttrUR4HQ==
-----END CERTIFICATE-----`,
    },
};

module.exports = pgConfig;
